name: Build & Deploy TastyFast application

on:
  push:
    branches:
      - brench1


jobs:
  build-deploy:
    name: Build and Deploy TastyFast application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file tasty-fast/pom.xml

      - name: Build the application
        run: |
          mvn clean 
          mvn -B package --file tasty-fast/pom.xml